### ISSUE TITLE
SQL Datenbank auf NAS auslagern und externen Zugriff ermöglichen

### ISSUE THREAD

**Issue by gelenkeharald** [gelenkeharald/lansuite#1]
MySQL server auf NAS (synology DS) laufen lassen. -> mariadb
Zugriffsberechtigungen setzen
Externe Erreichbarkeit über dyndns

**Comment by RoKi0815** [comment]
Relevante Punkte:
User erstellen
Rechte setzen (Host %)
Dyndns einrichten
Portnummern beachten
